name: CLT nightly tests

on:
  schedule:
    - cron: '00 20 * * *'

# cancels the previous workflow run when a new one appears in the same branch (e.g. master or a PR's branch)
concurrency:
  group: clt_nightly_${{ github.ref }}
  cancel-in-progress: true

jobs:
  clt_rhel_release_installation:
    if: github.event_name == 'workflow_dispatch'
    uses: manticoresoftware/clt/.github/workflows/clt-template.yml@v1
    with:
      docker_images: |
        [
          {"image": "centos:7"},
          {"image": "almalinux:8"},
          {"image": "almalinux:9"},
          {"image": "oraclelinux:9"},
          {"image": "amazonlinux:latest"}
        ]
      test_prefix: rhel-release-
  clt_deb_release_installation:
    if: github.event_name == 'workflow_dispatch'
    uses: manticoresoftware/clt/.github/workflows/clt-template.yml@v1
    with:
      docker_images: |
        [
          {"image": "ubuntu:bionic"},
          {"image": "ubuntu:focal"},
          {"image": "ubuntu:jammy"},
          {"image": "debian:buster"},
          {"image": "debian:bullseye"},
          {"image": "debian:bookworm"}
        ]
      test_prefix: deb-release-
